SET NOCOUNT ON;
SELECT PromptId,
 CASE WHEN CHARINDEX('2e59632d',ReferenceImages)>0 THEN 1 ELSE 0 END AS BagRef,
 CASE WHEN CHARINDEX('3a47870e',ReferenceImages)>0 THEN 1 ELSE 0 END AS HatRef,
 CASE WHEN PromptTextH3 LIKE N'%布包%' THEN 1 ELSE 0 END AS BagTxt,
 CASE WHEN PromptTextH3 LIKE N'%草帽%' THEN 1 ELSE 0 END AS HatTxt,
 CASE WHEN CHARINDEX('2e59632d',ReferenceImages)>0 THEN CHARINDEX('2e59632d',ReferenceImages) ELSE 0 END AS BagPos,
 CASE WHEN CHARINDEX('3a47870e',ReferenceImages)>0 THEN CHARINDEX('3a47870e',ReferenceImages) ELSE 0 END AS HatPos
FROM SeedancePrompts WHERE PromptId BETWEEN 5406 AND 5451 ORDER BY PromptId;
