SET NOCOUNT ON;
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND (TABLE_NAME LIKE N'%Video%' OR TABLE_NAME LIKE N'%Task%' OR TABLE_NAME LIKE N'%Shot%' OR TABLE_NAME LIKE N'%Frame%') ORDER BY TABLE_NAME;
SELECT N'=== 5412 urls ===';
SELECT PromptId, VideoUrl, LocalVideoUrl, Status, ShotLabel FROM SeedancePrompts WHERE PromptId = 5412;
